---
title: "Geoespacial 2"
---

Importando información

```{r}
library(sf)
library(dplyr)
```



```{r}
mx <- st_read("peru/departamentos/DEPARTAMENTOS.shp")
mx_data <- select(as.data.frame(mx), IDDPTO:DEPARTAMEN)
mx_geom <- st_geometry(mx)
mx <- st_sf(mx_data, geometry = mx_geom)

plot(mx_geom, border="white", col="lightblue", axes=T, cex.axis=0.5)

```

```{r}
departamento <- mx_data$DEPARTAMEN
plot(st_geometry(mx[departamento=="AMAZONAS",]), border="black", col="yellow", axes=T, cex.axis=0.5)

```

```{r}
library(Hmisc)
for(value in departamento){
  plot(st_geometry(mx[departamento==value,]), border="black", col="lightgreen", axes=T, main=value, cex.axis=0.5)
  minor.tick(nx=10, ny=10, tick.ratio=0.5)
}
```

```{r}
library(ggplot2)
ggplot(data=mx)+
  geom_sf(fill="greenyellow", color="black")
```

```{r}
library(ggspatial)

```

```{r}

library(RColorBrewer) # 
colourCount = length(unique(departamento))
getPalette = colorRampPalette(brewer.pal(30, "Spectral"))

ggplot(data=mx)+
  geom_sf(aes(fill=departamento))+
  scale_fill_manual(values = colorRampPalette(brewer.pal(12, "Accent"))(colourCount))+
  ggtitle("MAPA DEL PERÚ")+
  annotation_scale()+
  annotation_north_arrow(location='tl', height = unit(0.8, "cm"), width= unit(0.8, "cm"))
```

```{r}
ggplot(data=mx)+
  geom_sf(color="black", fill="greenyellow")+
  scale_fill_manual(values = colorRampPalette(brewer.pal(12, "Accent"))(colourCount))+
  ggtitle("MAPA DEL PERÚ")+
  annotation_scale()+
  annotation_north_arrow(location='tl', height = unit(0.8, "cm"), width= unit(0.8, "cm"))
```


```{r}
for(value in departamento){
graph <- ggplot(data=mx[departamento==value,])+
  geom_sf(color="black", fill="greenyellow")+
  ggtitle(value)+
  annotation_scale()+
  annotation_north_arrow(location='tl', height = unit(0.8, "cm"), width= unit(0.8, "cm"))
print(graph)
}

```

























